class TrainingType:
    # Legacy training types (for backwards compatibility)
    MNIST = 'MNIST'
    CHEST_X_RAY_PNEUMONIA = 'CHEST_X_RAY_PNEUMONIA'
    DETERMINISTIC_MNIST = 'DETERMINISTIC_MNIST'
    GOSSIP_MNIST = 'GOSSIP_MNIST'
    
    # Biomedical and statistical analysis types
    BIOMEDICAL_REGRESSION = 'BIOMEDICAL_REGRESSION'
    WEARABLE_ANALYTICS = 'WEARABLE_ANALYTICS'
    MEDICAL_IMAGE_BIOMARKER = 'MEDICAL_IMAGE_BIOMARKER'
    CARDIOVASCULAR_RISK = 'CARDIOVASCULAR_RISK'
    LAB_VALUE_PREDICTION = 'LAB_VALUE_PREDICTION'
    GENOMIC_ANALYSIS = 'GENOMIC_ANALYSIS'
    EPIDEMIOLOGICAL_MODELING = 'EPIDEMIOLOGICAL_MODELING'
    CLINICAL_OUTCOME_PREDICTION = 'CLINICAL_OUTCOME_PREDICTION'

